apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: zad1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        resources:
          limits:
            memory: 250Mi
            cpu: 250m
          requests:
            memory: 150Mi
            cpu: 150m

---
apiVersion: v1
kind: Service
metadata:
  name: php-apache-service
  namespace: zad1
spec:
  selector:
    app: php-apache
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80